In [12]:
import glob
import os
import re

import pandas as pd

files = glob.glob('./raw/gsheets/*編集用/行き先がないID.csv')
removed_ids= pd.DataFrame([])
for file in files:
    if os.path.getsize(file)<8:
        continue
    df = pd.read_csv(file)
    dir = os.path.basename(os.path.dirname(file))
    tab = re.match(r'(.+?)編集用',dir).group(1)
    df["タブ名"]=tab
    removed_ids = pd.concat([removed_ids,df.loc[:,["タブ名","H28ID","理由・コメント"]]],axis=0)

removed_ids

2305
2763
5145
13899

   タブ名          H28ID                理由・コメント
0   総合  F-03-05-08-01                    技能へ
1   総合  G-04-01-01-01                    技能へ
2   総合  G-04-01-03-01                    技能へ
3   総合  G-04-01-04-03                    技能へ
4   総合  G-04-01-05-01                    技能へ
..  ..            ...                    ...
95  技能  G-03-02-na-12       学生に求める手技ではない(近藤)
96  技能  G-03-03-na-06       学生に求める手技ではない(近藤)
97  技能  F-02-01-na-01  具体的に何を示すか不明、削除も検討(近藤)
98  技能  G-04-04-na-03         方略であったため削除(近藤)
99  技能  F-02-07-na-06       専門医のレベルなので削除(近藤)

[259 rows x 3 columns]